# Generated by Django 2.1.4 on 2018-12-27 23:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_auto_20181223_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('course', models.ForeignKey(default='Web Development', on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
