# Generated by Django 2.1.4 on 2019-01-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevents', '0002_auto_20190102_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='link',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='linkText',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='driveUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
