# Generated by Django 2.1.4 on 2018-12-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181223_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='courses.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='David Buckley', on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='courses.Teacher'),
        ),
    ]
