# Generated by Django 2.1.4 on 2019-01-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181223_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclosureDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driveUrl', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default='Web Development', on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
